name: Test find_lowest_number.py

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run tests
        run: |
          mkdir output_files  # Create output directory
          python3 find_lowest_number.py test_data/test1_input.txt output_files/test1_output.txt
          diff output_files/test1_output.txt test_data/test1_expected.txt
          
          python3 find_lowest_number.py test_data/test2_input.txt output_files/test2_output.txt
          diff output_files/test2_output.txt test_data/test2_expected.txt
          
          python3 find_lowest_number.py test_data/test3_input.txt output_files/test3_output.txt
          diff output_files/test3_output.txt test_data/test3_expected.txt
