name: Test find_lowest_number.py

on: 
  push:
    branches:
      - main  

jobs:
  automated_test:
    name: Assignment Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Debug Test Files
        run: |
          echo "Listing files in the repository:"
          ls -R
          
          echo "Contents of test1_input.txt:"
          cat test_data/test1_input.txt
          
          echo "Contents of test1_expected.txt:"
          cat test_data/test1_expected.txt

      - name: Produce test1_expected.txt output
        run: |
          mkdir output_files
          python3 find_lowest_number.py test_data/test1_input.txt output_files/test1_output.txt
          diff output_files/test1_output.txt test_data/test1_expected.txt

      - name: Produce test2_expected.txt output
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt output_files/test2_output.txt
          diff output_files/test2_output.txt test_data/test2_expected.txt

      - name: Produce test3_expected.txt output
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt output_files/test3_output.txt
          diff output_files/test3_output.txt test_data/test3_expected.txt
